<a href="https://colab.research.google.com/github/Jaggishah/Tensorflow_2.0/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
      [3,5,6]])
a2.shape

(2, 3)

In [8]:
import pandas as pd

ll = pd.DataFrame(a2)
ll

0  1  2
0  1  2  3
1  3  5  6

In [9]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[7, 3, 3, 3, 7],
       [4, 8, 9, 6, 6],
       [9, 6, 3, 6, 1]])

In [15]:
np.random.seed(0)
np.random.random((5,2))

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152]])

In [16]:
np.unique(random_array)

array([1, 3, 4, 6, 7, 8, 9])

In [17]:
a = [1,2,3]
sum(a)

6

In [18]:
np.sum(a)

6

In [19]:
a4 = np.random.random(1000)
a4

array([7.91725038e-01, 5.28894920e-01, 5.68044561e-01, 9.25596638e-01,
       7.10360582e-02, 8.71292997e-02, 2.02183974e-02, 8.32619846e-01,
       7.78156751e-01, 8.70012148e-01, 9.78618342e-01, 7.99158564e-01,
       4.61479362e-01, 7.80529176e-01, 1.18274426e-01, 6.39921021e-01,
       1.43353287e-01, 9.44668917e-01, 5.21848322e-01, 4.14661940e-01,
       2.64555612e-01, 7.74233689e-01, 4.56150332e-01, 5.68433949e-01,
       1.87898004e-02, 6.17635497e-01, 6.12095723e-01, 6.16933997e-01,
       9.43748079e-01, 6.81820299e-01, 3.59507901e-01, 4.37031954e-01,
       6.97631196e-01, 6.02254716e-02, 6.66766715e-01, 6.70637870e-01,
       2.10382561e-01, 1.28926298e-01, 3.15428351e-01, 3.63710771e-01,
       5.70196770e-01, 4.38601513e-01, 9.88373838e-01, 1.02044811e-01,
       2.08876756e-01, 1.61309518e-01, 6.53108325e-01, 2.53291603e-01,
       4.66310773e-01, 2.44425592e-01, 1.58969584e-01, 1.10375141e-01,
       6.56329589e-01, 1.38182951e-01, 1.96582362e-01, 3.68725171e-01,
      

In [20]:
%timeit sum(a4)
%timeit np.sum(a4)

133 µs ± 44.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
4.27 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
array1 = np.random.randint(10,size=(5,3))
array2 = np.random.randint(10,size=(5,3))

In [24]:
array1

array([[3, 0, 8],
       [8, 1, 8],
       [7, 5, 7],
       [9, 4, 0],
       [7, 2, 3]])

In [25]:
aray = np.dot(array1,array2.T)

In [26]:
aray

array([[ 59,  40,  56,  32,  75],
       [109,  44,  97,  72,  88],
       [116,  55,  89,  63, 110],
       [101,  16,  76,  72,  41],
       [ 85,  23,  70,  59,  50]])

In [27]:
data1 = np.random.randint(10,size=(5,3))

In [29]:
l1 = pd.DataFrame(data1,index=["Mon","Tue","Wed","Thu","Fri"],columns=['t','h','j'])
l1

t  h  j
Mon  4  9  0
Tue  3  0  7
Wed  0  8  1
Thu  2  8  5
Fri  8  2  1

In [30]:
import matplotlib.pyplot as plt
images = plt.imread('hero.jpeg')

In [31]:
images

array([[[118,  98, 195],
        [118,  98, 193],
        [120,  99, 194],
        ...,
        [228, 164, 180],
        [228, 164, 180],
        [229, 162, 179]],

       [[122, 101, 196],
        [122, 101, 196],
        [125, 101, 195],
        ...,
        [228, 166, 179],
        [228, 166, 179],
        [228, 166, 179]],

       [[128, 103, 197],
        [129, 104, 198],
        [130, 103, 196],
        ...,
        [228, 171, 178],
        [227, 170, 177],
        [227, 170, 177]],

       ...,

       [[ 56,  61, 143],
        [ 56,  61, 143],
        [ 56,  61, 143],
        ...,
        [ 88,  66, 131],
        [ 88,  66, 131],
        [ 88,  66, 131]],

       [[ 56,  63, 144],
        [ 56,  63, 144],
        [ 56,  63, 144],
        ...,
        [ 89,  67, 132],
        [ 89,  67, 132],
        [ 88,  66, 131]],

       [[ 56,  63, 144],
        [ 56,  63, 144],
        [ 56,  63, 144],
        ...,
        [ 89,  67, 132],
        [ 89,  67, 132],
        [ 88,  66, 131]]

In [33]:
images.dtype

dtype('uint8')