<a href="https://colab.research.google.com/github/Jaggishah/Tensorflow_2.0/blob/main/Tensorflow_basic_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print('TensorFlow Version:',tf.__version__)

TensorFlow Version: 2.12.0


In [13]:
mninst = tf.keras.datasets.mnist
(x_train,y_train),(x_test, y_test) = mninst.load_data()
x_train,x_test = x_train/255.0, x_test /255.0

In [14]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(124,activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [15]:
x_train.shape

(60000, 28, 28)

In [16]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.23617053,  0.24782977,  1.0113324 , -0.21929699, -0.23053326,
        -0.29142544, -0.08256541, -0.26932216,  0.530653  ,  0.222052  ]],
      dtype=float32)

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [18]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [19]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2971 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1462 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1101 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0902 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0783 - accuracy: 0.9754


In [20]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0777 - accuracy: 0.9772 - 1s/epoch - 4ms/step


[0.07770956307649612, 0.9771999716758728]

In [21]:
probality_model = tf.keras.Sequential([model,tf.keras.layers.Softmax()])

In [22]:
probality_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.9659385e-08, 1.0952160e-09, 9.2598663e-07, 2.9556966e-05,
        7.6226880e-10, 3.4412160e-08, 5.0953572e-13, 9.9996424e-01,
        8.1522660e-07, 4.4150243e-06],
       [4.4574031e-07, 6.6574003e-06, 9.9994099e-01, 1.9690209e-05,
        1.2840861e-16, 2.8260900e-05, 1.0285622e-08, 1.8491697e-15,
        3.9361794e-06, 2.5061268e-13],
       [6.0157339e-07, 9.9785918e-01, 4.4697896e-04, 3.5634839e-05,
        9.0919551e-05, 5.5993187e-05, 5.9874827e-05, 1.1792178e-03,
        2.6915435e-04, 2.4285639e-06],
       [9.9993455e-01, 5.3154120e-10, 3.4131692e-06, 2.1118149e-09,
        3.4095679e-06, 5.7264035e-08, 2.2596116e-05, 2.5484531e-05,
        2.3007154e-09, 1.0461743e-05],
       [1.7051331e-06, 3.8004288e-08, 7.2516859e-06, 3.7886119e-07,
        9.8781502e-01, 7.7432986e-08, 5.9663859e-07, 6.5486260e-05,
        1.5720389e-07, 1.2109375e-02]], dtype=float32)>